server:
  port: 11246

ajax:
  debug: true

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${mysql.username:root}
      password: ${mysql.password:FanDong}
      url: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/hmsrmyy-patient?characterEncoding=utf8
#      password: ${mysql.password:chinacaring}
#      url: jdbc:mysql://${mysql.host:101.132.74.234}:${mysql.port:3306}/pkzyy?characterEncoding=utf8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false


logging:
  level: info

# JWT
jwt:
  header: Authorization
  secret: caring
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: "session"
      refresh: "session"
      register: "user"
  allowPath: /depts,/schedule/**,/baseinfo/**,/session/**,/user,/swagger-resources/**,/webhooks/**,/session/**,/user/**,/v2/**,/swagger-resources/**,/webjars/**,/health/**,/info/**,/img/**,/third-party/**,/api/**,/admin/**,/trace/**,/applications/**,/env/**,/dump/**,/logfile/**,/metrics/**,/loggers/**,/jolokia/**,/refresh/**,/heapdump/**,/flyway/**,/liquibase/**,/auditevents/**,/danger/**,/depts,/prices,/price,/schedule/**,/message_wechat/**,/test/**,/alipay/form/**

#mybatis
mybatis-plus:
  mapper-locations: classpath:com/chinacaring/user/dao/mapper/xml/*Mapper.xml
#  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chinacaring.user.dao.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false