
package com.chinacaring.peixian.patient.client.wsdl.request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "quyiServiceNoSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuyiServiceNoSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.HelloWorldResponse")
    public String helloWorld();

    /**
     * 查取价格公示信息
     * 
     * @param itemCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryPriceBoardInfo", action = "http://tempuri.org/QueryPriceBoardInfo")
    @WebResult(name = "QueryPriceBoardInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPriceBoardInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPriceBoardInfo")
    @ResponseWrapper(localName = "QueryPriceBoardInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPriceBoardInfoResponse")
    public String queryPriceBoardInfo(
        @WebParam(name = "itemCode", targetNamespace = "http://tempuri.org/")
        String itemCode);

    /**
     * 住院患者信息查询
     * 
     * @param idType
     * @param name
     * @param idNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_inhos_patient_info", action = "http://tempuri.org/get_inhos_patient_info")
    @WebResult(name = "get_inhos_patient_infoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "get_inhos_patient_info", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetInhosPatientInfo")
    @ResponseWrapper(localName = "get_inhos_patient_infoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetInhosPatientInfoResponse")
    public String getInhosPatientInfo(
        @WebParam(name = "id_type", targetNamespace = "http://tempuri.org/")
        String idType,
        @WebParam(name = "id_no", targetNamespace = "http://tempuri.org/")
        String idNo,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 住院预交金查询
     * 
     * @param inpatientNo
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_inhos_patient_inbalance", action = "http://tempuri.org/get_inhos_patient_inbalance")
    @WebResult(name = "get_inhos_patient_inbalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "get_inhos_patient_inbalance", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetInhosPatientInbalance")
    @ResponseWrapper(localName = "get_inhos_patient_inbalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetInhosPatientInbalanceResponse")
    public String getInhosPatientInbalance(
        @WebParam(name = "inpatientNo", targetNamespace = "http://tempuri.org/")
        String inpatientNo,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 查询科室信息
     * 
     * @param deptCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeptInfo", action = "http://tempuri.org/GetDeptInfo")
    @WebResult(name = "GetDeptInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeptInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetDeptInfo")
    @ResponseWrapper(localName = "GetDeptInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetDeptInfoResponse")
    public String getDeptInfo(
        @WebParam(name = "deptCode", targetNamespace = "http://tempuri.org/")
        String deptCode);

    /**
     * 查询医生信息
     * 
     * @param doctCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDocInfo", action = "http://tempuri.org/GetDocInfo")
    @WebResult(name = "GetDocInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDocInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetDocInfo")
    @ResponseWrapper(localName = "GetDocInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetDocInfoResponse")
    public String getDocInfo(
        @WebParam(name = "doctCode", targetNamespace = "http://tempuri.org/")
        String doctCode);

    /**
     * 查询检验信息
     * 
     * @param beginDate
     * @param endDate
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLisResultInfo", action = "http://tempuri.org/GetLisResultInfo")
    @WebResult(name = "GetLisResultInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLisResultInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetLisResultInfo")
    @ResponseWrapper(localName = "GetLisResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetLisResultInfoResponse")
    public String getLisResultInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 查询检查信息
     * 
     * @param beginDate
     * @param endDate
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPacsResultInfo", action = "http://tempuri.org/GetPacsResultInfo")
    @WebResult(name = "GetPacsResultInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPacsResultInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPacsResultInfo")
    @ResponseWrapper(localName = "GetPacsResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPacsResultInfoResponse")
    public String getPacsResultInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 查询住院检验信息
     * 
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetZYLisResultInfo", action = "http://tempuri.org/GetZYLisResultInfo")
    @WebResult(name = "GetZYLisResultInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetZYLisResultInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetZYLisResultInfo")
    @ResponseWrapper(localName = "GetZYLisResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetZYLisResultInfoResponse")
    public String getZYLisResultInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo);

    /**
     * 查询住院检查信息
     * 
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetZYPacsResultInfo", action = "http://tempuri.org/GetZYPacsResultInfo")
    @WebResult(name = "GetZYPacsResultInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetZYPacsResultInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetZYPacsResultInfo")
    @ResponseWrapper(localName = "GetZYPacsResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetZYPacsResultInfoResponse")
    public String getZYPacsResultInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo);

    /**
     * 查询患者在医院中卡号通过实物卡
     * 
     * @param name
     * @param mcardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPatientCardNo", action = "http://tempuri.org/GetPatientCardNo")
    @WebResult(name = "GetPatientCardNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatientCardNo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPatientCardNo")
    @ResponseWrapper(localName = "GetPatientCardNoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPatientCardNoResponse")
    public String getPatientCardNo(
        @WebParam(name = "mcardNo", targetNamespace = "http://tempuri.org/")
        String mcardNo,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 查询患者在医院中卡号
     * 
     * @param iden
     * @param name
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPatientCardNo1", action = "http://tempuri.org/GetPatientCardNo1")
    @WebResult(name = "GetPatientCardNo1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPatientCardNo1", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPatientCardNo1")
    @ResponseWrapper(localName = "GetPatientCardNo1Response", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetPatientCardNo1Response")
    public String getPatientCardNo1(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "iden", targetNamespace = "http://tempuri.org/")
        String iden);

    /**
     * 新建患者信息
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertPatientInfo", action = "http://tempuri.org/InsertPatientInfo")
    @WebResult(name = "InsertPatientInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertPatientInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertPatientInfo")
    @ResponseWrapper(localName = "InsertPatientInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertPatientInfoResponse")
    public String insertPatientInfo(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 直接挂号、预约转挂号
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertRegisterTemp", action = "http://tempuri.org/InsertRegisterTemp")
    @WebResult(name = "InsertRegisterTempResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertRegisterTemp", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertRegisterTemp")
    @ResponseWrapper(localName = "InsertRegisterTempResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertRegisterTempResponse")
    public String insertRegisterTemp(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 查询午别信息
     * 
     * @param noonCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetNoonInfo", action = "http://tempuri.org/GetNoonInfo")
    @WebResult(name = "GetNoonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetNoonInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetNoonInfo")
    @ResponseWrapper(localName = "GetNoonInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetNoonInfoResponse")
    public String getNoonInfo(
        @WebParam(name = "noonCode", targetNamespace = "http://tempuri.org/")
        String noonCode);

    /**
     * 查询排班信息
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShemaInfo", action = "http://tempuri.org/GetShemaInfo")
    @WebResult(name = "GetShemaInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetShemaInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfo")
    @ResponseWrapper(localName = "GetShemaInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfoResponse")
    public String getShemaInfo(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 查询排班信息可通过科室或者医生查询
     * 
     * @param beginDate
     * @param endDate
     * @param deptCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShemaInfoNew", action = "http://tempuri.org/GetShemaInfoNew")
    @WebResult(name = "GetShemaInfoNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetShemaInfoNew", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfoNew")
    @ResponseWrapper(localName = "GetShemaInfoNewResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfoNewResponse")
    public String getShemaInfoNew(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "deptCode", targetNamespace = "http://tempuri.org/")
        String deptCode);

    /**
     * 查询作废的排班信息
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShemaInfoNoVaild", action = "http://tempuri.org/GetShemaInfoNoVaild")
    @WebResult(name = "GetShemaInfoNoVaildResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetShemaInfoNoVaild", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfoNoVaild")
    @ResponseWrapper(localName = "GetShemaInfoNoVaildResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaInfoNoVaildResponse")
    public String getShemaInfoNoVaild(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 【暂未开放】查询预约时间点信息
     * 
     * @param shemaId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetShemaPointInfo", action = "http://tempuri.org/GetShemaPointInfo")
    @WebResult(name = "GetShemaPointInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetShemaPointInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaPointInfo")
    @ResponseWrapper(localName = "GetShemaPointInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetShemaPointInfoResponse")
    public String getShemaPointInfo(
        @WebParam(name = "shemaId", targetNamespace = "http://tempuri.org/")
        String shemaId);

    /**
     * 预约挂号、取消预约挂号
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertBooking", action = "http://tempuri.org/InsertBooking")
    @WebResult(name = "InsertBookingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertBooking", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertBooking")
    @ResponseWrapper(localName = "InsertBookingResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertBookingResponse")
    public String insertBooking(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 插入住院预约金
     * 
     * @param patientName
     * @param payMode
     * @param operCode
     * @param fee
     * @param rechargeTime
     * @param inpatientSeq
     * @param transNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "inhos_patient_inbalance_recharge", action = "http://tempuri.org/inhos_patient_inbalance_recharge")
    @WebResult(name = "inhos_patient_inbalance_rechargeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "inhos_patient_inbalance_recharge", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InhosPatientInbalanceRecharge")
    @ResponseWrapper(localName = "inhos_patient_inbalance_rechargeResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InhosPatientInbalanceRechargeResponse")
    public String inhosPatientInbalanceRecharge(
        @WebParam(name = "inpatient_seq", targetNamespace = "http://tempuri.org/")
        String inpatientSeq,
        @WebParam(name = "patient_name", targetNamespace = "http://tempuri.org/")
        String patientName,
        @WebParam(name = "oper_code", targetNamespace = "http://tempuri.org/")
        String operCode,
        @WebParam(name = "pay_mode", targetNamespace = "http://tempuri.org/")
        String payMode,
        @WebParam(name = "fee", targetNamespace = "http://tempuri.org/")
        String fee,
        @WebParam(name = "recharge_time", targetNamespace = "http://tempuri.org/")
        String rechargeTime,
        @WebParam(name = "trans_no", targetNamespace = "http://tempuri.org/")
        String transNo);

    /**
     * 查询挂号状态2为已看诊,0为未看诊,3为退号
     * 
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRegState", action = "http://tempuri.org/GetRegState")
    @WebResult(name = "GetRegStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegState", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegState")
    @ResponseWrapper(localName = "GetRegStateResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegStateResponse")
    public String getRegState(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode);

    /**
     * 查询挂号状态2为已看诊,1为未看诊,3为退号
     * 
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRegisterStatus", action = "http://tempuri.org/GetRegisterStatus")
    @WebResult(name = "GetRegisterStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegisterStatus", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegisterStatus")
    @ResponseWrapper(localName = "GetRegisterStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegisterStatusResponse")
    public String getRegisterStatus(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode);

    /**
     * 查询预约挂号状态
     * 
     * @param bookId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBookingState", action = "http://tempuri.org/GetBookingState")
    @WebResult(name = "GetBookingStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetBookingState", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetBookingState")
    @ResponseWrapper(localName = "GetBookingStateResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetBookingStateResponse")
    public String getBookingState(
        @WebParam(name = "bookId", targetNamespace = "http://tempuri.org/")
        String bookId);

    /**
     * 获取时间范围内挂号信息
     * 
     * @param internalDays
     * @param name
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRegInfoByCardNoOrName", action = "http://tempuri.org/GetRegInfoByCardNoOrName")
    @WebResult(name = "GetRegInfoByCardNoOrNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRegInfoByCardNoOrName", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegInfoByCardNoOrName")
    @ResponseWrapper(localName = "GetRegInfoByCardNoOrNameResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRegInfoByCardNoOrNameResponse")
    public String getRegInfoByCardNoOrName(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "internalDays", targetNamespace = "http://tempuri.org/")
        String internalDays);

    /**
     * 获取排队叫号表
     * 
     * @param beginDate
     * @param endDate
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetQueue", action = "http://tempuri.org/GetQueue")
    @WebResult(name = "GetQueueResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetQueue", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueue")
    @ResponseWrapper(localName = "GetQueueResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueueResponse")
    public String getQueue(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 【暂未开放】挂号、预约转挂号(临时表)医保脱卡支付
     * 
     * @param input
     * @param readSiReturn
     * @param operCode
     * @param chargeSiReturn
     * @param ybInvoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertSIRegisterTemp", action = "http://tempuri.org/InsertSIRegisterTemp")
    @WebResult(name = "InsertSIRegisterTempResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertSIRegisterTemp", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertSIRegisterTemp")
    @ResponseWrapper(localName = "InsertSIRegisterTempResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.InsertSIRegisterTempResponse")
    public String insertSIRegisterTemp(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "chargeSiReturn", targetNamespace = "http://tempuri.org/")
        String chargeSiReturn,
        @WebParam(name = "readSiReturn", targetNamespace = "http://tempuri.org/")
        String readSiReturn,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode,
        @WebParam(name = "ybInvoice", targetNamespace = "http://tempuri.org/")
        String ybInvoice);

    /**
     * 查询非APP挂号记录
     * 
     * @param iden
     * @param name
     * @param cardNo
     * @param phoneNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryZDBookingInfo", action = "http://tempuri.org/QueryZDBookingInfo")
    @WebResult(name = "QueryZDBookingInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryZDBookingInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryZDBookingInfo")
    @ResponseWrapper(localName = "QueryZDBookingInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryZDBookingInfoResponse")
    public String queryZDBookingInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "iden", targetNamespace = "http://tempuri.org/")
        String iden,
        @WebParam(name = "phoneNo", targetNamespace = "http://tempuri.org/")
        String phoneNo);

    /**
     * 查询所有挂号信息
     * 
     * @param iden
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryAppRegistRecords", action = "http://tempuri.org/QueryAppRegistRecords")
    @WebResult(name = "QueryAppRegistRecordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryAppRegistRecords", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryAppRegistRecords")
    @ResponseWrapper(localName = "QueryAppRegistRecordsResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryAppRegistRecordsResponse")
    public String queryAppRegistRecords(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "iden", targetNamespace = "http://tempuri.org/")
        String iden);

    /**
     * 查询所有预约信息
     * 
     * @param inden
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryAppAppointRecords", action = "http://tempuri.org/QueryAppAppointRecords")
    @WebResult(name = "QueryAppAppointRecordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryAppAppointRecords", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryAppAppointRecords")
    @ResponseWrapper(localName = "QueryAppAppointRecordsResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryAppAppointRecordsResponse")
    public String queryAppAppointRecords(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "inden", targetNamespace = "http://tempuri.org/")
        String inden);

    /**
     * 查询APP挂号对账信息
     * 
     * @param beginDate
     * @param endDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryQuYiRegInfo", action = "http://tempuri.org/QueryQuYiRegInfo")
    @WebResult(name = "QueryQuYiRegInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryQuYiRegInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryQuYiRegInfo")
    @ResponseWrapper(localName = "QueryQuYiRegInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryQuYiRegInfoResponse")
    public String queryQuYiRegInfo(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate);

    /**
     * 查询APP挂号对账信息根据收费工号
     * 
     * @param beginDate
     * @param endDate
     * @param operCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryRegInfoOper", action = "http://tempuri.org/QueryRegInfoOper")
    @WebResult(name = "QueryRegInfoOperResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryRegInfoOper", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryRegInfoOper")
    @ResponseWrapper(localName = "QueryRegInfoOperResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryRegInfoOperResponse")
    public String queryRegInfoOper(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode);

    /**
     * 查询APP挂号对账信息根据收费工号含医保
     * 
     * @param beginDate
     * @param endDate
     * @param operCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryRegInfoOperSi", action = "http://tempuri.org/QueryRegInfoOperSi")
    @WebResult(name = "QueryRegInfoOperSiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryRegInfoOperSi", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryRegInfoOperSi")
    @ResponseWrapper(localName = "QueryRegInfoOperSiResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryRegInfoOperSiResponse")
    public String queryRegInfoOperSi(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode);

    /**
     * 门诊结算
     * 
     * @param payMode
     * @param operCode
     * @param recipeNo
     * @param totCost
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveFee", action = "http://tempuri.org/SaveFee")
    @WebResult(name = "SaveFeeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveFee", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.SaveFee")
    @ResponseWrapper(localName = "SaveFeeResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.SaveFeeResponse")
    public String saveFee(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode,
        @WebParam(name = "payMode", targetNamespace = "http://tempuri.org/")
        String payMode,
        @WebParam(name = "totCost", targetNamespace = "http://tempuri.org/")
        String totCost);

    /**
     * 【暂未开放】门诊结算医保拖卡支付
     * 
     * @param readSiReturn
     * @param payMode
     * @param operCode
     * @param recipeNo
     * @param totCost
     * @param clinicCode
     * @param chargeSiReturn
     * @param ybInvoice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SaveSIFee", action = "http://tempuri.org/SaveSIFee")
    @WebResult(name = "SaveSIFeeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveSIFee", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.SaveSIFee")
    @ResponseWrapper(localName = "SaveSIFeeResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.SaveSIFeeResponse")
    public String saveSIFee(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode,
        @WebParam(name = "payMode", targetNamespace = "http://tempuri.org/")
        String payMode,
        @WebParam(name = "totCost", targetNamespace = "http://tempuri.org/")
        String totCost,
        @WebParam(name = "chargeSiReturn", targetNamespace = "http://tempuri.org/")
        String chargeSiReturn,
        @WebParam(name = "readSiReturn", targetNamespace = "http://tempuri.org/")
        String readSiReturn,
        @WebParam(name = "ybInvoice", targetNamespace = "http://tempuri.org/")
        String ybInvoice);

    /**
     * 【暂未开放】获取辅材信息
     * 
     * @param recipeNo
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFcInfo", action = "http://tempuri.org/GetFcInfo")
    @WebResult(name = "GetFcInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFcInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFcInfo")
    @ResponseWrapper(localName = "GetFcInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFcInfoResponse")
    public String getFcInfo(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo);

    /**
     * 【暂未开放】删除辅材信息
     * 
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteFcInfo", action = "http://tempuri.org/DeleteFcInfo")
    @WebResult(name = "DeleteFcInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteFcInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.DeleteFcInfo")
    @ResponseWrapper(localName = "DeleteFcInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.DeleteFcInfoResponse")
    public String deleteFcInfo(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode);

    /**
     * 获取病人收费信息
     * 
     * @param isFee
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFeeListByClinicCode", action = "http://tempuri.org/GetFeeListByClinicCode")
    @WebResult(name = "GetFeeListByClinicCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFeeListByClinicCode", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFeeListByClinicCode")
    @ResponseWrapper(localName = "GetFeeListByClinicCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFeeListByClinicCodeResponse")
    public String getFeeListByClinicCode(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "isFee", targetNamespace = "http://tempuri.org/")
        String isFee);

    /**
     * 获取病人收费信息含单位
     * 
     * @param isFee
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFeeListByClinicCode1", action = "http://tempuri.org/GetFeeListByClinicCode1")
    @WebResult(name = "GetFeeListByClinicCode1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFeeListByClinicCode1", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFeeListByClinicCode1")
    @ResponseWrapper(localName = "GetFeeListByClinicCode1Response", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetFeeListByClinicCode1Response")
    public String getFeeListByClinicCode1(
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "isFee", targetNamespace = "http://tempuri.org/")
        String isFee);

    /**
     * 获取门诊缴费记录查询(退费记录)
     * 
     * @param name
     * @param recipeNo
     * @param invoiceNo
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOutpfreeRecordsStatus", action = "http://tempuri.org/GetOutpfreeRecordsStatus")
    @WebResult(name = "GetOutpfreeRecordsStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOutpfreeRecordsStatus", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOutpfreeRecordsStatus")
    @ResponseWrapper(localName = "GetOutpfreeRecordsStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOutpfreeRecordsStatusResponse")
    public String getOutpfreeRecordsStatus(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo);

    /**
     * 获取门诊缴费记录查询
     * 
     * @param name
     * @param recipeNo
     * @param invoiceNo
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOutpfreeRecordsNewStatus", action = "http://tempuri.org/GetOutpfreeRecordsNewStatus")
    @WebResult(name = "GetOutpfreeRecordsNewStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOutpfreeRecordsNewStatus", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOutpfreeRecordsNewStatus")
    @ResponseWrapper(localName = "GetOutpfreeRecordsNewStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOutpfreeRecordsNewStatusResponse")
    public String getOutpfreeRecordsNewStatus(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo,
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo);

    /**
     * 查取门诊费用主表
     * 
     * @param name
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceInfo", action = "http://tempuri.org/QueryInvoiceInfo")
    @WebResult(name = "QueryInvoiceInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfo")
    @ResponseWrapper(localName = "QueryInvoiceInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfoResponse")
    public String queryInvoiceInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

    /**
     * 查取门诊费用主表传操作员
     * 
     * @param beginDate
     * @param endDate
     * @param operCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceInfoOper", action = "http://tempuri.org/QueryInvoiceInfoOper")
    @WebResult(name = "QueryInvoiceInfoOperResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceInfoOper", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfoOper")
    @ResponseWrapper(localName = "QueryInvoiceInfoOperResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfoOperResponse")
    public String queryInvoiceInfoOper(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode);

    /**
     * 【暂未开放】查取门诊费用主表传操作员含医保
     * 
     * @param beginDate
     * @param endDate
     * @param operCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceInfoOperSi", action = "http://tempuri.org/QueryInvoiceInfoOperSi")
    @WebResult(name = "QueryInvoiceInfoOperSiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceInfoOperSi", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfoOperSi")
    @ResponseWrapper(localName = "QueryInvoiceInfoOperSiResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceInfoOperSiResponse")
    public String queryInvoiceInfoOperSi(
        @WebParam(name = "beginDate", targetNamespace = "http://tempuri.org/")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        String endDate,
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode);

    /**
     * 查取门诊费用明细表
     * 
     * @param invoiceNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInvoiceMxInfo", action = "http://tempuri.org/QueryInvoiceMxInfo")
    @WebResult(name = "QueryInvoiceMxInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInvoiceMxInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceMxInfo")
    @ResponseWrapper(localName = "QueryInvoiceMxInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInvoiceMxInfoResponse")
    public String queryInvoiceMxInfo(
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo);

    /**
     * 查询处方主信息
     * 
     * @param clinicNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryPrescriptionInfo", action = "http://tempuri.org/QueryPrescriptionInfo")
    @WebResult(name = "QueryPrescriptionInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPrescriptionInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrescriptionInfo")
    @ResponseWrapper(localName = "QueryPrescriptionInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrescriptionInfoResponse")
    public String queryPrescriptionInfo(
        @WebParam(name = "clinicNo", targetNamespace = "http://tempuri.org/")
        String clinicNo);

    /**
     * 查询处方药品信息
     * 
     * @param recipeNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryPrescriptionMedicione", action = "http://tempuri.org/QueryPrescriptionMedicione")
    @WebResult(name = "QueryPrescriptionMedicioneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPrescriptionMedicione", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrescriptionMedicione")
    @ResponseWrapper(localName = "QueryPrescriptionMedicioneResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrescriptionMedicioneResponse")
    public String queryPrescriptionMedicione(
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo);

    /**
     * 查询在院患者住院费用
     * 
     * @param iden
     * @param name
     * @param inDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInMainInfo", action = "http://tempuri.org/QueryInMainInfo")
    @WebResult(name = "QueryInMainInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInMainInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInMainInfo")
    @ResponseWrapper(localName = "QueryInMainInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInMainInfoResponse")
    public String queryInMainInfo(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "iden", targetNamespace = "http://tempuri.org/")
        String iden,
        @WebParam(name = "inDate", targetNamespace = "http://tempuri.org/")
        String inDate);

    /**
     * 查询在院患者费用记录
     * 
     * @param inPatientNo
     * @param patientNo
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryInMainMxInfo", action = "http://tempuri.org/QueryInMainMxInfo")
    @WebResult(name = "QueryInMainMxInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryInMainMxInfo", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInMainMxInfo")
    @ResponseWrapper(localName = "QueryInMainMxInfoResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryInMainMxInfoResponse")
    public String queryInMainMxInfo(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "inPatientNo", targetNamespace = "http://tempuri.org/")
        String inPatientNo,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo);

    /**
     * 查询病人住院费用信息
     * 
     * @param inPatientNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryPrefeeMaster", action = "http://tempuri.org/QueryPrefeeMaster")
    @WebResult(name = "QueryPrefeeMasterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPrefeeMaster", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrefeeMaster")
    @ResponseWrapper(localName = "QueryPrefeeMasterResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPrefeeMasterResponse")
    public String queryPrefeeMaster(
        @WebParam(name = "inPatientNo", targetNamespace = "http://tempuri.org/")
        String inPatientNo);

    /**
     * 查取住院结算主表
     * 
     * @param inden
     * @param inTimes
     * @param patient
     * @param name
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryBalanceHead", action = "http://tempuri.org/QueryBalanceHead")
    @WebResult(name = "QueryBalanceHeadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryBalanceHead", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryBalanceHead")
    @ResponseWrapper(localName = "QueryBalanceHeadResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryBalanceHeadResponse")
    public String queryBalanceHead(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "inTimes", targetNamespace = "http://tempuri.org/")
        String inTimes,
        @WebParam(name = "patient", targetNamespace = "http://tempuri.org/")
        String patient,
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name,
        @WebParam(name = "inden", targetNamespace = "http://tempuri.org/")
        String inden);

    /**
     * 查取住院结算明细表
     * 
     * @param patientNo
     * @param invoiceNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryBalanceDetail", action = "http://tempuri.org/QueryBalanceDetail")
    @WebResult(name = "QueryBalanceDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryBalanceDetail", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryBalanceDetail")
    @ResponseWrapper(localName = "QueryBalanceDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryBalanceDetailResponse")
    public String queryBalanceDetail(
        @WebParam(name = "invoiceNo", targetNamespace = "http://tempuri.org/")
        String invoiceNo,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo);

    /**
     * 查取住院诊断表
     * 
     * @param patientNo
     * @param cardNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryPatientDiag", action = "http://tempuri.org/QueryPatientDiag")
    @WebResult(name = "QueryPatientDiagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryPatientDiag", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPatientDiag")
    @ResponseWrapper(localName = "QueryPatientDiagResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.QueryPatientDiagResponse")
    public String queryPatientDiag(
        @WebParam(name = "cardNo", targetNamespace = "http://tempuri.org/")
        String cardNo,
        @WebParam(name = "patientNo", targetNamespace = "http://tempuri.org/")
        String patientNo);

    /**
     * 获取医保挂号上传明细
     * 
     * @param input
     * @param cardInfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSIRegUpload", action = "http://tempuri.org/GetSIRegUpload")
    @WebResult(name = "GetSIRegUploadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSIRegUpload", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIRegUpload")
    @ResponseWrapper(localName = "GetSIRegUploadResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIRegUploadResponse")
    public String getSIRegUpload(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "cardInfo", targetNamespace = "http://tempuri.org/")
        String cardInfo);

    /**
     * 获取医保收费上传明细
     * 
     * @param input
     * @param cardInfo
     * @param recipeNo
     * @param clinicCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSIFeeUpload", action = "http://tempuri.org/GetSIFeeUpload")
    @WebResult(name = "GetSIFeeUploadResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSIFeeUpload", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIFeeUpload")
    @ResponseWrapper(localName = "GetSIFeeUploadResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIFeeUploadResponse")
    public String getSIFeeUpload(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input,
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo,
        @WebParam(name = "clinicCode", targetNamespace = "http://tempuri.org/")
        String clinicCode,
        @WebParam(name = "cardInfo", targetNamespace = "http://tempuri.org/")
        String cardInfo);

    /**
     * 获取医保挂号结算入参
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSIRegBalance", action = "http://tempuri.org/GetSIRegBalance")
    @WebResult(name = "GetSIRegBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSIRegBalance", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIRegBalance")
    @ResponseWrapper(localName = "GetSIRegBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIRegBalanceResponse")
    public String getSIRegBalance(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 获取医保挂号结算入参
     * 
     * @param input
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSIFeeBalance", action = "http://tempuri.org/GetSIFeeBalance")
    @WebResult(name = "GetSIFeeBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSIFeeBalance", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIFeeBalance")
    @ResponseWrapper(localName = "GetSIFeeBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetSIFeeBalanceResponse")
    public String getSIFeeBalance(
        @WebParam(name = "input", targetNamespace = "http://tempuri.org/")
        String input);

    /**
     * 查询门诊处方收据的退款状态，此接口为了对账
     * 
     * @param receiptNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecieptRefundStatus", action = "http://tempuri.org/GetRecieptRefundStatus")
    @WebResult(name = "GetRecieptRefundStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecieptRefundStatus", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRecieptRefundStatus")
    @ResponseWrapper(localName = "GetRecieptRefundStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRecieptRefundStatusResponse")
    public String getRecieptRefundStatus(
        @WebParam(name = "receiptNum", targetNamespace = "http://tempuri.org/")
        String receiptNum);

    /**
     * 查询门诊处方的缴费，执行，退款状态
     * 
     * @param recipeNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRecieptStatus", action = "http://tempuri.org/GetRecieptStatus")
    @WebResult(name = "GetRecieptStatusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecieptStatus", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRecieptStatus")
    @ResponseWrapper(localName = "GetRecieptStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetRecieptStatusResponse")
    public String getRecieptStatus(
        @WebParam(name = "recipeNo", targetNamespace = "http://tempuri.org/")
        String recipeNo);

    /**
     * 根据时间段查询此操作员下的所有订单信息，查询我方操作员的订单信息，此接口为了对账
     * 
     * @param operCode
     * @param beginTime
     * @param endTime
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOrderInfoByOperCode", action = "http://tempuri.org/GetOrderInfoByOperCode")
    @WebResult(name = "GetOrderInfoByOperCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrderInfoByOperCode", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOrderInfoByOperCode")
    @ResponseWrapper(localName = "GetOrderInfoByOperCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetOrderInfoByOperCodeResponse")
    public String getOrderInfoByOperCode(
        @WebParam(name = "operCode", targetNamespace = "http://tempuri.org/")
        String operCode,
        @WebParam(name = "beginTime", targetNamespace = "http://tempuri.org/")
        String beginTime,
        @WebParam(name = "endTime", targetNamespace = "http://tempuri.org/")
        String endTime);

}
