
package com.chinacaring.peixian.patient.client.wsdl.request;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceCallInterface", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://172.17.10.236:81/WebServiceCallInterface_wx.asmx?wsdl")
public class WebServiceCallInterface
    extends Service
{

    private final static URL WEBSERVICECALLINTERFACE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECALLINTERFACE_EXCEPTION;
    private final static QName WEBSERVICECALLINTERFACE_QNAME = new QName("http://tempuri.org/", "WebServiceCallInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.17.10.236:81/WebServiceCallInterface_wx.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECALLINTERFACE_WSDL_LOCATION = url;
        WEBSERVICECALLINTERFACE_EXCEPTION = e;
    }

    public WebServiceCallInterface() {
        super(__getWsdlLocation(), WEBSERVICECALLINTERFACE_QNAME);
    }

    public WebServiceCallInterface(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECALLINTERFACE_QNAME, features);
    }

    public WebServiceCallInterface(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECALLINTERFACE_QNAME);
    }

    public WebServiceCallInterface(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECALLINTERFACE_QNAME, features);
    }

    public WebServiceCallInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCallInterface(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCallInterfaceSoap
     */
    @WebEndpoint(name = "WebServiceCallInterfaceSoap")
    public WebServiceCallInterfaceSoap getWebServiceCallInterfaceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WebServiceCallInterfaceSoap"), WebServiceCallInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCallInterfaceSoap
     */
    @WebEndpoint(name = "WebServiceCallInterfaceSoap")
    public WebServiceCallInterfaceSoap getWebServiceCallInterfaceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WebServiceCallInterfaceSoap"), WebServiceCallInterfaceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceCallInterfaceSoap
     */
    @WebEndpoint(name = "WebServiceCallInterfaceSoap12")
    public WebServiceCallInterfaceSoap getWebServiceCallInterfaceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "WebServiceCallInterfaceSoap12"), WebServiceCallInterfaceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceCallInterfaceSoap
     */
    @WebEndpoint(name = "WebServiceCallInterfaceSoap12")
    public WebServiceCallInterfaceSoap getWebServiceCallInterfaceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WebServiceCallInterfaceSoap12"), WebServiceCallInterfaceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECALLINTERFACE_EXCEPTION!= null) {
            throw WEBSERVICECALLINTERFACE_EXCEPTION;
        }
        return WEBSERVICECALLINTERFACE_WSDL_LOCATION;
    }

}
