
package com.chinacaring.peixian.patient.client.wsdl.request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceCallInterfaceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceCallInterfaceSoap {


    /**
     * 通过本接口可以查询患者当天的排队叫号信息
     * 
     * @param sParams
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_queue_for_patient", action = "http://tempuri.org/get_queue_for_patient")
    @WebResult(name = "get_queue_for_patientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "get_queue_for_patient", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueueForPatient")
    @ResponseWrapper(localName = "get_queue_for_patientResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueueForPatientResponse")
    public String getQueueForPatient(
        @WebParam(name = "sParams", targetNamespace = "http://tempuri.org/")
        String sParams);

    /**
     * 通过本接口可以查询所有科室的当天排队叫号信息
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "get_queue_by_dept", action = "http://tempuri.org/get_queue_by_dept")
    @WebResult(name = "get_queue_by_deptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "get_queue_by_dept", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueueByDept")
    @ResponseWrapper(localName = "get_queue_by_deptResponse", targetNamespace = "http://tempuri.org/", className = "com.chinacaring.peixian.patient.client.wsdl.request.GetQueueByDeptResponse")
    public String getQueueByDept();

}
